DROP DATABASE IF EXISTS practice1;

CREATE SCHEMA practice1 DEFAULT CHARACTER SET utf8mb4;

use practice1;

SELECT 'CREATING DATABASE STRUCTURE' as 'INFO';

CREATE TABLE users(
    user_no INT AUTO_INCREMENT PRIMARY KEY ,
    user_id VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)