DROP DATABASE IF EXISTS sypedia;

CREATE SCHEMA sypedia DEFAULT CHARACTER SET utf8mb4;

use sypedia;

SELECT 'CREATING DATABASE STRUCTURE' as 'INFO';

CREATE TABLE users(
    user_no INT AUTO_INCREMENT PRIMARY KEY ,
    user_id VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)